# -*- coding: utf-8 -*-
#"Midterm Exam

#Automatically generated by Colab.

#Original file is located at
#    https://colab.research.google.com/drive/1eYhCElLNdglRUx2dMKGJ6WDvIzbQ3VvZ

# Data Analysis : SYN Flood attacks on ADNU VideoCon Router.

#On January 28, 2020, numerous attacks were logged in ADNU Video Conferencing Router/Gateway. A SYN flood (half-open attack) is a type of denial-of-service (DDoS) attack which aims to make a server unavailable to legitimate traffic by consuming all available server resources.

#By repeatedly sending initial connection request (SYN) packets, the attacker is able to overwhelm all available ports on a targeted server machine, causing the targeted device to respond to legitimate traffic sluggishly or not at all (Source: [link text](https://www.cloudflare.com/learning/ddos/syn-flood-ddos-attack/)).

#The data consists of the following variable:

#* Time - The time, in PST, when the attack occurred
#* Protocol - The network protocol used
#*Source IP - The remote IP address (ie, the attacker)
#* Source Port - The remote port number (of the attacker)
#* Destination IP - The IP address of the router/gateway (ie, device being attacked)
#* Source Port - The port number of the application or service being attacked (Note! 0 through 1023 are well-known ports) Instructions

#Your task is to analyze the data and see who's behind the attack as well as the mode. Load the data attacks.csv [link text](https://drive.google.com/file/d/1JrKP7S4sHxZNm5hMd2D3vyNiO4MIi5fc/view?usp=sharing) then answer the questions below.

#For each question,  explain your answer in
##detail.


#---
#"

# Load the data of DDoS attacks
AtkData = read.csv("attacks.csv")

# Load ggplot library
library(ggplot2)

##"### 1. What is the distribution of attack times throughout the day?

#"

# Type your R commands here

# extracts all unique timestamps within the data
atkMin <- as.POSIXct(names(table(AtkData$Time)), format = "%m/%d/%Y %H:%M")
# counts how many times the attack occured within the specific time
atkFreq <- as.numeric(table(AtkData$Time))

table(atkMin, atkDist)

plot(atkMin, atkDist,
    type = "b",
    main = "Distribution of DDoS Attacks (01/28/20)",
    xlab = "Time",
    ylab = "Frequency")

#"*Explain your answer here:*

#This graph explains the distribution of DDoS attacks, using the time and frequency of the attack. The variable "atkMin" is used to collect unique values from the data, while the variable "atkFreq" counts the occurences of each unique value.


#To show the relationship between the time and frequency, we used plot(), where "atkMin" is the x and "atkFreq" is the y. The attacks happened somewhere between 17:51 (05:51 PM) to 18:03 (06:03 PM), which is approximately 12 minutes long.

### 2. Create a histogram to show the distribution of attack frequencies by hour of the day. Explain the distribution of attack frequencies by hour of the day based on the histogram.
#"

# Type your R commands here

# Convert Time to POSIXct and extract the hour as numeric
AtkData$Time <- as.numeric(format(as.POSIXct(AtkData$Time, format = "%m/%d/%Y %H:%M"), "%H"))

hist(AtkData$Time,
     breaks = 24,
     main = "Histogram of Attack Frequencies by Hour of the Day",
     xlab = "Hour of the Day",
     ylab = "Frequency of Attacks",
     col = "skyblue",
     border = "black")

# Using ggplot()
# Extract the hour from AtkData$Time
atkHour <- data.frame(hour = as.numeric(format(as.POSIXct(AtkData$Time, format = "%m/%d/%Y %H:%M"), "%H")))

# Create the histogram
ggplot(atkHour, aes(x = hour)) +
    geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
    labs(title = "Frequency of Attacks by Hour of the Day",
       x = "Hour of the Day",
       y = "Frequency of Attacks") +
    scale_x_continuous(breaks = seq(0, 23, by = 1)) +
    theme_bw()

#"*Explain your answer here: *

#This graph explains the distribution of attacks based on the hour of the day using histogram. We used the variable "atkHour" to extract the frequency of data based on the hour of the attack. In the graph, approximately over 400 attacks happened at 17:00 (05:00 PM), while under 50 attacks happened at 18:00 (06:00 PM).

### 3. Create a bar chart to show the top 5 most common source IP addresses. Explain the significance of the top 5 most common source IP addresses based on the bar chart.
#"

# Type your R commands here

countIPs = sort(table(AtkData$SourceIP), decreasing = TRUE)
topIPs = head(countIPs, 5)

barplot(topIPs,
        main = "Top 5 Most Common Source IP Addresses",
        xlab = "Source IP Address",
        ylab = "Frequency of Attacks",
        col = "skyblue",
        border = "black",
        las = 2)

#"*Explain your answer here:*

#This graph explains the top 5 most common IP addresses from the data using a bar graph. We used the two variables "countIPs" and "topIPs" to sort data in terms of frequency and take the top 5 respectively. Then, we used the barplot() to show the data we gathered.

#It is important to gather the top most common IP addresses during the attacks because it would help us track or identify its source, mitigate or even prevent their attacks, and understand their attack patterns, that would potentially help and/or improve the security's infrastructure.

### 4. From which single IP address did most of the attacks come from? Do an Internet search and learn about the location (eg, Country, ISP) of this IP address.
#"

# Type your R commands here

# sorts source IPs to highest to lowest
countIPs = sort(table(AtkData$SourceIP), decreasing = TRUE)
# takes the highest of the source IPs
commonIPs = names(countIPs)[1]

message("The most common IP address is: ", commonIPs)

#"5. At what specific time did most attacks occur?"""

# Type your R commands here

# sorts attack times to highest to lowest
countTime = sort(table(AtkData$Time), decreasing = TRUE)
# takes the highest of the attack times
commonHour = names(countTime)[1]

message("Most attacks occured at: ", commonHour)

#"*Explain your answer here:*

##The single IP address in which most attacks come from is "51.174.71.252", which is located at Kristiansand, Agder, Norway. Its service provider is the Altibox AS, a Norwegian internet service provider (ISP). Most of the attacks happened at 17:55 (05:55 PM) of the same day.

#To extract the data, we used table() to extract the frequency of each timestamps and sort() in decreasing order, to sort the data from highest to lowest. We then used names()[1] to extract the highest or most frequent in the data.

#### 6. What particular applications or services were attacked? Do an Internet search about what application or services listens or uses a particular port number, especially, the well-known ports
#"

# Type your R commands here

# sorts the destination ports from highest to lowest
PORTCount = sort(table(AtkData$DestinationPort), decreasing = TRUE)

# we then used a for loop to iterate over the sorted destination ports
for (i in 1 : length(TOPPorts)) {
    cat("Port: ", names(PORTCount)[i], " : Number of Attacks: ", PORTCount[i], "\n")
}

#"*Explain your answer here:*

#The data above shows the destination ports that are attacked by SYN attacks. At the top spot we have the Port 443 that has a count of 359 attacks. This port is typically associated with HTTPS, which suggests that the majority of attacks were secure web services. Next is the Port 5223 that has a count of 41 attacks. This port is often associated with APNS (Apple Push Notification Service) which suggests that the attack attacks Apple-related services. Lastly is the Port 23 that has a count of 5. This is a default Telnet port, used for remote command-line access to network devices. Other ports such as Port 37606 and Port 51430 is not well known, but may be associated wit less commonly used application or service.

#### 7. What particular network protocols were used in the attacks?
#"

# Type your R commands here

# we used sort() to sort the collected data of network protocols, from highest to lowest
ProtocolC = sort(table(AtkData$Protocol), decreasing = TRUE)

ProtocolC

#"*Explain your answer here:*

#The particular network protocols that were used during the attacks are TCP (Transmission Control Protocol) and ICMP (Internet Control Message Protocol). TPC is the highest which has a frequency of 350, and ICMP came to the second which has a frequency of 67. TCP is used in making sure that communication between computers over a network is reliable, while ICPM is used for error reporting and diagnostic functions.

### 8. Create a boxplot to compare the distribution of source port numbers for different network protocols. Explain the differences in the distribution of source port numbers for different network protocols based on the boxplot.
#"

# Type your R commands here

TCP = AtkData$SourcePort[AtkData$Protocol == "TCP"]
ICMP = AtkData$SourcePort[AtkData$Protocol == "ICMP"]

boxplot(list(TCP = TCP, ICMP = ICMP),
    main = "Distribution of Source Port for Different Network Protocols",
    xlab = "Network Protocol",
    ylab = "Source Port Number",
    col = c("gold", "royal blue"),
    border = "black")

#"*Explain your answer here.*

#This graph shows the distribution of source port for different network protocols using boxplot analysis. TCP ranges under 20000 to over 60000 source ports, while ICMP covers approximately 40000 to 60000 source ports. The TCP's 3rd quartile is almost as the same as ICMPs, but its median is almost as the same as ICMP's first quartile. One notable thing about the ICMP is that its median is the same as its 3rd quartile, and it has an outlier (denoted by the little circle below) located between 30000 and 40000.

#### 9. Create a histogram to show the distribution of attack frequencies by day of the week. Explain the distribution of attack frequencies by day of the week based on the histogram.
#"

# off by 1 (may be deleted soon)
# atkDay is focused on the day
atkDay <- as.numeric(format(as.POSIXct(AtkData$Time, format = "%m/%d/%Y %H:%M"), "%d"))

# Create a histogram, adjust breaks to cover atkDay (which is 28)
hist(atkDay,
     breaks = seq(min(atkDay) - 2, max(atkDay) + 1, by = 1), # Breaks to cover the range of atkDay
     main = "Histogram of Attack Frequencies by Day of the Month", # Changed title for clarity
     xlab = "Day of the Month", # Changed x-axis label for clarity
     ylab = "Frequency of Attacks",
     col = "skyblue",
     border = "black")

# Type your R commands here

# using ggplot()
atkDay <- data.frame(hour = as.numeric(format(as.POSIXct(AtkData$Time, format = "%m/%d/%Y %H:%M"), "%d")))

# Create the histogram
ggplot(atkDay, aes(x = hour)) +
    geom_histogram(binwidth = 1, fill = "skyblue", color = "black", boundary = 0.5) +
    labs(title = "Frequency of Attacks by Day of the Month (January)",
         x = "Day of the Month",
         y = "Frequency of Attacks") +
    scale_x_continuous(breaks = seq(1, 31, by = 1), limits = c(0.5, 31.5)) +
    theme_bw()

#"*Explain your answer here.*

#The graph shows the day of the month where most attacks happened, using histogram. In the graph, only the day 28 has all of the attacks, whereas the rest is empty. This means that the attack only happened on January 28.

#### 10.  Create a scatter plot to show the relationship between the time of day and the frequency of attacks. Explain the relationship between the time of day and the frequency of attacks based on the scatter plot.
#"

# Type your R commands here

# Extract unique times and corresponding frequencies
atkTime <- as.POSIXct(names(table(AtkData$Time)), format = "%m/%d/%Y %H:%M") # extract unique values in POSIXct format
atkFreq <- as.numeric(table(AtkData$Time)) # extract the corresponding frequencies

# Create a scatterplot
plot(atkTime, atkFreq,
     main = "Scatterplot of Time of attacks and their Frequency",
     xlab = "Time (minutes)",
     ylab = "Frequency",
     col = "blue", pch = 19)

#"*Explain your answer here.*

#This graph show the relationship between the time of day and the frequency of attacks using scatterplot analysis. The lowest among the attacks happened at 17:51 (05:51 PM) and the highest happened at 17:55 (05:55 PM). Most of the attacks happened between 17:52 and 17:57, with the drop happened afterwards between 17:58
#"